/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelRouteImport } from './routes/reel'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArRouteImport } from './routes/ar'
import { Route as IndexRouteImport } from './routes/index'

const ReelRoute = ReelRouteImport.update({
  id: '/reel',
  path: '/reel',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRoute
  '/passport': typeof PassportRoute
  '/reel': typeof ReelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRoute
  '/passport': typeof PassportRoute
  '/reel': typeof ReelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRoute
  '/passport': typeof PassportRoute
  '/reel': typeof ReelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ar' | '/dashboard' | '/passport' | '/reel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ar' | '/dashboard' | '/passport' | '/reel'
  id: '__root__' | '/' | '/ar' | '/dashboard' | '/passport' | '/reel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRoute
  DashboardRoute: typeof DashboardRoute
  PassportRoute: typeof PassportRoute
  ReelRoute: typeof ReelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reel': {
      id: '/reel'
      path: '/reel'
      fullPath: '/reel'
      preLoaderRoute: typeof ReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRoute,
  DashboardRoute: DashboardRoute,
  PassportRoute: PassportRoute,
  ReelRoute: ReelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
